
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION = 13;
  public static final int GUION = 12;
  public static final int PUNTO = 7;
  public static final int DOSPUNTOS = 4;
  public static final int CADENA = 16;
  public static final int LETRA = 18;
  public static final int ALLAVE = 2;
  public static final int BARRA = 10;
  public static final int FLECHA = 6;
  public static final int ID = 19;
  public static final int COMA = 9;
  public static final int CLLAVE = 3;
  public static final int EOF = 0;
  public static final int ASTERISCO = 8;
  public static final int CONJ = 14;
  public static final int ESPECIAL = 21;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int PUNTOCOMA = 5;
  public static final int MAS = 11;
  public static final int ACCI = 20;
  public static final int PORCENTAJES = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALLAVE",
  "CLLAVE",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "FLECHA",
  "PUNTO",
  "ASTERISCO",
  "COMA",
  "BARRA",
  "MAS",
  "GUION",
  "INTERROGACION",
  "CONJ",
  "PORCENTAJES",
  "CADENA",
  "NUMERO",
  "LETRA",
  "ID",
  "ACCI",
  "ESPECIAL"
  };
}

